-- 戦国パスポート Ver2.0: 国家ダッシュボード関連の拡張。
-- 既存テーブルは変更せず、列追加とテーブル追加のみで対応する。

-- ============================================================
-- users: 国民証・創設メンバー/建国メンバーの受け皿
-- ============================================================

alter table users
  -- 国民番号。既存行にも自動採番される(identity列は ALTER TABLE ADD COLUMN 時に
  -- 既存行へ連番をバックフィルする)。
  add column national_number bigint generated by default as identity,
  add column contribution_points int not null default 0,
  -- 創設メンバー(既存の土地オーナーを将来紐付ける想定。Ver2.0では手動フラグのみ)
  add column is_founding_member boolean not null default false,
  add column development_plot_id text,
  add column founding_member_number int,
  -- 建国メンバー(10〜30万円商品の購入者を将来紐付ける想定。Ver2.0では手動フラグのみ)
  add column is_nation_builder boolean not null default false,
  add column nation_builder_plan text,
  add column nation_builder_joined_at timestamptz;

create unique index idx_users_founding_member_number on users(founding_member_number)
  where founding_member_number is not null;

-- ============================================================
-- 本日の任務: 完璧な管理はせず、日付単位の達成ログのみ持つ。
-- 任務の定義(キー・タイトル・判定方法)は src/lib/daily-missions.ts で管理する。
-- ============================================================

create table daily_mission_completions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id),
  mission_key text not null,
  completed_date date not null default current_date,
  created_at timestamptz not null default now(),
  unique (user_id, mission_key, completed_date)
);

create index idx_daily_mission_completions_user_date on daily_mission_completions(user_id, completed_date);

alter table daily_mission_completions enable row level security;
